/**
 * AC - A source-code copy detector
 *
 *     For more information please visit:  http://github.com/manuel-freire/ac
 *
 * ****************************************************************************
 *
 * This file is part of AC, version 2.0
 *
 * AC is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * AC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with AC.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * AtomicExpressionPanel.java
 *
 * Created on September 13, 2006, 8:00 PM
 */

package es.ucm.fdi.ac.expression;

import es.ucm.fdi.ac.expression.Expression;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author  mfreire
 */
public class AtomicExpressionPanel extends ExpressionPanel {

	private Expression e;

	/**
	 * Creates new form AtomicExpressionPanel
	 */
	public AtomicExpressionPanel(CompositeExpressionPanel parentPanel) {
		super(parentPanel);
		initComponents();
	}

	public void setExpression(Expression e) {

		this.e = e;

		ComboBoxModel model = new DefaultComboBoxModel(e.getHeaders().toArray());
		jcbType.setModel(model);

		jtfPattern.setText(e.getBody());

		repaint();
	}

	public Expression getExpression() {
		return e;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jcbType = new javax.swing.JComboBox();
		jtfPattern = new javax.swing.JTextField();
		jbDelete = new javax.swing.JButton();
		jbTest = new javax.swing.JButton();

		setLayout(new java.awt.GridBagLayout());

		jcbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));
		jcbType.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jcbTypeActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
		add(jcbType, gridBagConstraints);

		jtfPattern.setText("jTextField1");
		jtfPattern
				.setToolTipText("<html>Generalmente, esto es una expresion regular Java:<br>\n<table><tr><td>EXPRESION</td><td>SIGNIFICADO</td></tr>\n<tr><td>.*\\.c</td><td>ficheros que acaban en '.c' (. = cualquier caracter, \\. = un punto, * = 0 o mas veces) </tr><tr><td>[pP]0?2.*</td><td>ficheros que empiezan por P mayuscula o minuscula, <br> y luego contienen un 0 opcional (? = opcional) y un dos, y luego lo que sea\n</tr><tr><td>public *static *void *main</td><td>el fichero Java contiene un 'main'<br>\n(en una hipotética busqueda \"por contenidos\")</td></th></table>\n</html>");
		jtfPattern.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusLost(java.awt.event.FocusEvent evt) {
				jtfPatternFocusLost(evt);
			}
		});
		jtfPattern.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jtfPatternKeyTyped(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 2);
		add(jtfPattern, gridBagConstraints);

		jbDelete.setText("Eliminar");
		jbDelete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbDeleteActionPerformed(evt);
			}
		});
		jbDelete.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jbDeleteMousePressed(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jbDeleteMouseReleased(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(3, 4, 3, 4);
		add(jbDelete, gridBagConstraints);

		jbTest.setText("Probar");
		jbTest.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbTestActionPerformed(evt);
			}
		});
		jbTest.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jbTestMousePressed(evt);
			}

			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jbTestMouseReleased(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
		add(jbTest, gridBagConstraints);
	}// </editor-fold>//GEN-END:initComponents

	private void jbTestMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTestMouseReleased
		// TODO add your handling code here:
		setSelected(false);
		repaint();
	}//GEN-LAST:event_jbTestMouseReleased

	private void jbDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDeleteMouseReleased
		// TODO add your handling code here:
		setSelected(false);
		repaint();
	}//GEN-LAST:event_jbDeleteMouseReleased

	private void jbDeleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDeleteMousePressed
		// TODO add your handling code here:
		setSelected(true);
		repaint();
	}//GEN-LAST:event_jbDeleteMousePressed

	private void jbTestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTestMousePressed
		// TODO add your handling code here:
		setSelected(true);
		repaint();
	}//GEN-LAST:event_jbTestMousePressed

	private void jbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTestActionPerformed
		// TODO add your handling code here:
		test(true);
	}//GEN-LAST:event_jbTestActionPerformed

	private void jtfPatternFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPatternFocusLost
		// TODO add your handling code here:
		e.setBody(jtfPattern.getText());
	}//GEN-LAST:event_jtfPatternFocusLost

	private void jcbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTypeActionPerformed
		// TODO add your handling code here:
		e.setHeader((String) jcbType.getSelectedItem());
		jtfPattern.setText(e.getBody());
	}//GEN-LAST:event_jcbTypeActionPerformed

	private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
		// TODO add your handling code here:
		parentPanel.deleteSubexp(this);
	}//GEN-LAST:event_jbDeleteActionPerformed

	private void jtfPatternKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPatternKeyTyped
		// TODO add your handling code here:
		e.setBody(jtfPattern.getText());
	}//GEN-LAST:event_jtfPatternKeyTyped

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbDelete;
	private javax.swing.JButton jbTest;
	private javax.swing.JComboBox jcbType;
	private javax.swing.JTextField jtfPattern;
	// End of variables declaration//GEN-END:variables

}
