/**
 * AC - A source-code copy detector
 *
 *     For more information please visit:  http://github.com/manuel-freire/ac
 *
 * ****************************************************************************
 *
 * This file is part of AC, version 2.0
 *
 * AC is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * AC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with AC.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Extract.java
 *
 * Created on September 18, 2006, 12:08 PM
 */

package es.ucm.fdi.ac.extract;

import es.ucm.fdi.util.I18N;
import static es.ucm.fdi.util.I18N.m;

import java.io.File;
import java.util.Locale;

/**
 *
 * @author  mfreire
 */
public class Extractor extends javax.swing.JFrame {

	private ZipSelectionPanel zsp;

	/**
	 * Creates new form Extract
	 */
	public Extractor() {
		initComponents();
		zsp = new ZipSelectionPanel();
		getContentPane().add(zsp);
		setSize(1000, 600);
		setLocation(100, 100);
		setTitle(m("Extract.Title"));
		repaint();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		I18N.setLang(Locale.getDefault().getLanguage());
		final String[] argCopy = (String[]) args.clone();
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Extractor e = new Extractor();
				e.setVisible(true);
				for (String s : argCopy) {
					File f = new File(s);
					e.zsp.addFile(f);
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}
